# Site settings
title: "ckosmas.com"
name: "Chris Kosmas"
email: "chris@ckosmas.com"
url: "https://ckosmas.com"
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author profile settings
author:
  name   : "Chris Kosmas"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I like to break things and then fix them. This is my personal blog containing posts about information security topics I find interesting."
  location: "Greater Chicago Area"
  github: ckosmas
  email: chris@ckosmas.com
  
  links:
  
  #  - label: "Website"
   #   icon: "fas fa-fw fa-link"
    #  url: "https://ckosmas.com"

footer:
  links:
    #- label: "GitHub"
      #icon: "fab fa-fw fa-github"
      #url: "https://github.com/ckosmas"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
